## Slightly more advanced pandas demo
1. Access a CSV file from https://www.ncdc.noaa.gov/snow-and-ice/daily-snow/ using pandas
    <br>Skip an extraneous header row
2. Report the data, columns, number of rows
3. Subset for one county ; subset fields
4. Retrieve the unique values from a column with .unique
5. Calculate the mean values for each county with groupby

Created by Elizabeth Tulanowski, GIS Instructor + Geospatial Centroid Education Coordinator, Colorado State University

### 1. Access a CSV file using pandas and skip an extraneous row

In [64]:
# import libraries
import pandas as pd, os

# paths to data
url = r"https://www.ncdc.noaa.gov/snow-and-ice/daily-snow/CO-snow-depth-202103.csv"

# Read the CSV
# Data has extraneous row at the top. Using skiprows to overlook it.  (df.drop did not seem to work, but that's a typical method for removing rows)

df = pd.read_csv(url, skiprows =1)

print (f"Data frame for {url} has been created.")

Data frame for https://www.ncdc.noaa.gov/snow-and-ice/daily-snow/CO-snow-depth-202103.csv has been created.

### 2. Report the data, columns, and number of rows
Want to drop columns? # https://www.activestate.com/resources/quick-reads/how-to-delete-a-column-row-from-a-dataframe/

In [7]:
# print first 5 rows
print (df.head())

# List the column names (https://www.geeksforgeeks.org/how-to-get-column-names-in-pandas-dataframe/)
for col in df.columns:
    print(col)

       GHCN ID     Station Name      County     State  Elevation  Latitude  \
0  USC00050105    AGUILAR 18WSW  LAS ANIMAS  Colorado       8642     37.32
1  US1COLA0033  AGUILAR 7.2 WSW  LAS ANIMAS  Colorado       7216     37.36
2  US1COWA0016      AKRON 1.9NE  WASHINGTON  Colorado       4602     40.18
3  USC00050109        AKRON 4 E  WASHINGTON  Colorado       4541     40.16
4  USC00050128       ALAMOSA 1E     ALAMOSA  Colorado       7538     37.47

   Longitude Mar 1 Mar 2 Mar 3  ...   Mar 22 Mar 23 Mar 24 Mar 25 Mar 26  \
0    -104.95   2.0   1.0     T  ...      1.0    1.0   12.0    8.0    4.0
1    -104.77   0.5     T     T  ...      1.9      T    8.0    7.5    4.0
2    -103.19     M     M     M  ...        M      M      M      M      M
3    -103.14   0.0   0.0   0.0  ...      0.0    0.0    0.0    0.0    0.0
4    -105.86   0.0   0.0   0.0  ...      0.0    0.0    1.0    0.0    0.0

  Mar 27 Mar 28 Mar 29 Mar 30 Mar 31
0    2.0      T    0.0    0.0    0.0
1      T      T      T      T    0.0
2      M      M      M      M      M
3    0.0    0.0    0.0    0.0    0.0
4    0.0    0.0    0.0    0.0    0.0

[5 rows x 38 columns]
GHCN ID
Station Name
County
State
Elevation
Latitude
Longitude
Mar 1
Mar 2
Mar 3
Mar 4
Mar 5
Mar 6
Mar 7
Mar 8
Mar 9
Mar 10
Mar 11
Mar 12
Mar 13
Mar 14
Mar 15
Mar 16
Mar 17
Mar 18
Mar 19
Mar 20
Mar 21
Mar 22
Mar 23
Mar 24
Mar 25
Mar 26
Mar 27
Mar 28
Mar 29
Mar 30
Mar 31

#### Get the total number of rows in the data frame

In [6]:
len(df)

print (f"There are {len(df)} records in the table")

There are 721 records in the table

### 3. Subset / Select just Larimer county & return only a few columns

In [63]:
Larimer = df[df.County == 'LARIMER']
cols = ["GHCN ID", "Station Name", "County", "Elevation", "Mar 1", "Mar 2"]
Larimer[cols]

         GHCN ID               Station Name   County  Elevation Mar 1 Mar 2
33   US1COLR0252               BELLVUE 1 NW  LARIMER       5245     T     M
34   US1COLR0360             BELLVUE 4.9 NE  LARIMER       5145     M     M
35   US1COLR0004              BELLVUE 5.9 W  LARIMER       6612   3.5   3.0
38   US1COLR1222           BERTHOUD 2.0 SSW  LARIMER       4986     M     M
39   US1COLR1239             BERTHOUD 2.3 N  LARIMER       5132   0.0   0.0
40   US1COLR1200             BERTHOUD 2.5 N  LARIMER       5138     M     M
41   US1COLR1136           BERTHOUD 3.0 NNW  LARIMER       5157     M     M
42   US1COLR1231           BERTHOUD 3.2 WSW  LARIMER       5125     M     M
43   US1COLR0922           BERTHOUD 4.4 WSW  LARIMER       5180     T   0.0
102  USC00051060           BUCKHORN MTN 1 E  LARIMER       7398   3.0   1.0
111  US1COLR1235            CAMPION 1.8 NNE  LARIMER       5034     M     M
236  US1COLR1026              DRAKE 4.3 WSW  LARIMER       6945     M     M
264  US1COLR1115           ESTES PARK 1.7 W  LARIMER       7956     M     M
265  US1COLR0767           ESTES PARK 1.8 S  LARIMER       7938   2.5   2.0
266  US1COLR0987         ESTES PARK 1.8 SSE  LARIMER       7640     T     T
267  US1COLR1019         ESTES PARK 10.5 SE  LARIMER       6730     M     M
268  US1COLR0247         ESTES PARK 3.3 SSW  LARIMER       8092   2.8   1.5
285  US1COLR0255                        FCL  LARIMER       5009     T     T
286  US1COLR0270                 FCL 1.7 SE  LARIMER       4996     M     M
287  US1COLR0320                 FCL 1.7 SW  LARIMER       5071     T     T
288  US1COLR0273                 FCL 2.2 NW  LARIMER       5066     T     T
289  US1COLR0311                 FCL 2.3 NW  LARIMER       5075     T     T
290  US1COLR0259                  FCL 2.5 W  LARIMER       5117     T     T
291  US1COLR0340                FCL 2.55 NE  LARIMER       4976   0.5     M
292  US1COLR0391                 FCL 3.0 SW  LARIMER       5140   0.5     T
293  US1COLR0284                  FCL 3.0 W  LARIMER       5219     M     M
294  US1COLR0307                 FCL 3.2 NE  LARIMER       5029     M     M
295  US1COLR0393                  FCL 5.6 E  LARIMER       4917   0.0   0.0
298  USC00052934         FLATIRON RESERVOIR  LARIMER       5503   1.0   0.0
303  USC00053005               FORT COLLINS  LARIMER       5003   0.0   0.0
..           ...                        ...      ...        ...   ...   ...
503  US1COLR0464                  LOV 5.0 S  LARIMER       5140     M     M
504  US1COLR1240            LOVELAND 12.7 W  LARIMER       6707     M   0.2
505  US1COLR0662           LOVELAND 2.0 SSE  LARIMER       4963     M     M
506  US1COLR0854            LOVELAND 2.3 NW  LARIMER       5090     T     T
507  US1COLR0676            LOVELAND 2.4 NW  LARIMER       5097     T     M
508  US1COLR0687             LOVELAND 2.7 E  LARIMER       4986   0.5   0.3
509  US1COLR1109           LOVELAND 2.8 WNW  LARIMER       5158     T     T
510  USC00055236                LOVELAND 2N  LARIMER       5079     T     T
511  US1COLR0104           LOVELAND 3.0 NNE  LARIMER       4983     T     T
512  US1COLR1125             LOVELAND 3.2 E  LARIMER       4958     M     M
515  US1COLR0050                LYONS 4.8 N  LARIMER       5616     T     T
516  US1COLR0735               LYONS 6.4 NW  LARIMER       6665   2.0   1.5
517  US1COLR1072              LYONS 8.9 WNW  LARIMER       7623     M     M
600  US1COLR0329         RED FEATHER 5.9 NE  LARIMER       7921   3.0   1.5
601  US1COLR0815  RED FEATHER LAKES 3.8 ENE  LARIMER       7321     M     M
617  US1COLR1168              RUSTIC 11.2 W  LARIMER       7902     M     M
618  USC00057296                RUSTIC 9WSW  LARIMER       7695     T     T
667  US1COLR1016             TIMNATH 2.1 SE  LARIMER       4839   0.0   0.0
668  US1COLR0948             TIMNATH 2.2 SE  LARIMER       4835     M     M
669  US1COLR0036            TIMNATH 4.1 NNE  LARIMER       5032     T     T
680  USC00058690        VIRGINIA DALE 7 ENE  LARIMER       7013   5.0   4.0
681  US1COLR0672      VIRGINIA DALE 7.2 SSW  LARIMER       6720     M     M
689  USC00058839                  WATERDALE  LARIMER       5229   0.0   0.0
691  US1COLR0142                 WEL 1.8 NE  LARIMER       5261     M     M
692  US1COLR0952          WELLINGTON 0.4 NW  LARIMER       5219     M     M
693  US1COLR1008          WELLINGTON 0.8 SW  LARIMER       5194     T     T
694  US1COLR0918         WELLINGTON 3.7 WNW  LARIMER       5313     M     M
711  US1COLR1059             WINDSOR 2.6 SW  LARIMER       4963     M     M
712  US1COLR1110             WINDSOR 2.9 SW  LARIMER       4949     M     M
714  US1COLR0845            WINDSOR 3.8 WSW  LARIMER       4948     T     T

[96 rows x 6 columns]

#### How many records are there in just Larimer County?

In [9]:
# Do you remember how to do this from above?

#### How can you return some simple statistics from a column?

In [11]:
# Get the average elevation from the Elevation column

print ("The mean elevation for all stations is:")
print ("\t" + str(df.mean()["Elevation"]))
print ("The mean elevation for Larimer county is:")
print ("\t" + str(Larimer.mean()["Elevation"]))

The mean elevation for all stations is:
	6134.679611650486
The mean elevation for Larimer county is:
	5541.145833333333

In [10]:
# Stats for the Larimer-only data.  Mar 1 and Mar 2 fields don't show up because they have text values in the field
Larimer.describe()

         Elevation   Latitude   Longitude
count    96.000000  96.000000   96.000000
mean   5541.145833  40.522812 -105.153229
std     943.759771   0.143062    0.169901
min    4835.000000  40.270000 -105.780000
25%    4995.750000  40.410000 -105.172500
50%    5093.500000  40.540000 -105.095000
75%    5360.500000  40.610000 -105.060000
max    8092.000000  40.970000 -104.950000

### 4. Get the unique values from the County column:

In [62]:
unqCounties = df.County.unique()
print (unqCounties)

#Want it sorted? It's a numpy array, so use numpy's sort method:
import numpy
print(numpy.sort(unqCounties))


# How many counties are there?
print(len(unqCounties))

['ADAMS' 'ALAMOSA' 'ARAPAHOE' 'ARCHULETA' 'BACA' 'BENT' 'BOULDER'
 'BROOMFIELD' 'CHAFFEE' 'CHEYENNE' 'CLEAR CREEK' 'CONEJOS' 'COSTILLA'
 'CROWLEY' 'CUSTER' 'DELTA' 'DENVER' 'DOLORES' 'DOUGLAS' 'EAGLE' 'EL PASO'
 'ELBERT' 'FREMONT' 'GARFIELD' 'GILPIN' 'GRAND' 'GUNNISON' 'HUERFANO'
 'JACKSON' 'JEFFERSON' 'KIOWA' 'KIT CARSON' 'LA PLATA' 'LAKE' 'LARIMER'
 'LAS ANIMAS' 'LINCOLN' 'LOGAN' 'MESA' 'MINERAL' 'MOFFAT' 'MONTEZUMA'
 'MONTROSE' 'MORGAN' 'OTERO' 'OURAY' 'PARK' 'PHILLIPS' 'PITKIN' 'PROWERS'
 'PUEBLO' 'RIO BLANCO' 'RIO GRANDE' 'ROUTT' 'SAGUACHE' 'SAN JUAN'
 'SAN MIGUEL' 'SEDGWICK' 'SUMMIT' 'TELLER' 'WASHINGTON' 'WELD' 'YUMA']
63

#### 4. Calculate counts and average values for each county
Reference: https://realpython.com/pandas-groupby/

In [79]:
grp = df.groupby("County").count()
grp.head()

elev = df.groupby("County")["Elevation"].mean()
print(elev)

cnty = "Larimer"
#Get value for just one county:
print (f"\nAverage elevation for {cnty}: " + str(round(elev.LARIMER,2)))

County
ADAMS         5226.000000
ALAMOSA       7796.333333
ARAPAHOE      5680.421053
ARCHULETA     7658.833333
BACA          4307.333333
                 ...
SUMMIT        8963.142857
TELLER        9094.285714
WASHINGTON    4563.833333
WELD          4918.781250
YUMA          3917.727273
Name: Elevation, Length: 62, dtype: float64

Average elevation for Larimer: 5507.12

#### Calculate the total snow for each county for one date

This one is extra tricky because the column contains both numbers and string, and the values are all being read as strings. Despite my best efforts, I can't -yet- get them read as numbers. But the battle is not over, and I'll keep working on it.

In [ ]:
# Using just Larimer county as a test...

#Read each value, and try to convert to integer
for ind in Larimer.index:
    val = (Larimer["Mar 2"][ind])
    try:
        val2 = int(val)
        print (val2)
    except ValueError:
        isInt = False
    if isInt:
        print (val2)
    else:
        print ("stuck as string")

# Another option- use isdigit or isinteger in an if statement.
#     if val.isdigit()==True:
#         print (val)
#     else:
#         print (val)
    

# Next step would be to either replace M and T values with 0, then do a .sum
# or add each numeric value to a list, then calculate sum of each county and report each value

#### 5. Check that the table updated

In [72]:
# #Do we have a new column?
# print ("\nThe columns are now:")
# for col in df.columns:
#     print(col)

# # Return data again with df.head()
# print ()
# print (df.head(10))

# All this is done in memory in the data frame. It must be exported to a new CSV.
filename = url.split("/")[-1]
path = r"C:\student\pandasDemo"
newfile = os.path.join(path,filename[:-4]+ "_updated.csv")
print ("The updated table is saved as "+ newfile)
df.to_csv(os.path.join(path,newfile))

The updated table is saved as C:\student\pandasDemo\CO-snow-depth-202103_updated.csv

### Pandas resources:
There is no shortage of resources and sample code out there. Here are a few to get you going:

pandas documentation: https://pandas.pydata.org/docs/index.html<br>
Videos: https://www.youtube.com/playlist?list=PL-osiE80TeTsWmV9i9c58mdDCSskIFdDS <br>
Tutorials and guides: https://www.w3resource.com/pandas/index.php

### The end. Thanks for watching, and Happy Coding!